/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Comments: () => import('#controllers/comments_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Places: () => import('#controllers/places_controller'),
  Posts: () => import('#controllers/posts_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Ratings: () => import('#controllers/ratings_controller'),
}
